version: '3'

services:
  nodeapp:
    build: .
    ports:
    - "3000:3000"
    tty: true
    command: nodemon bin/www
    volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules
    network_mode: host
    container_name: nodeapp